apiVersion: v1
kind: ReplicationController
metadata:
  name: demo83
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: demo83
  template:
    metadata:
      labels:
        app: demo83
    spec:
      serviceAccount: YOUR
      containers:
      - name: demo83
        image: ${docker-registry}/${docker-namespace}/demo83:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080